  
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  FS_METHOD: direct
  WP_DEBUG: "false"
  WP_DEBUG_LOG: "false"
  WP_DEBUG_DISPLAY: "false"
  WP_POST_REVISIONS: "3"
  DB_HOST: wordpress-mysql
  DB_NAME: wordpress-mysql
  DB_CHARSET: utf8mb4