apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD:  root_password 
  MYSQL_DATABASE: wordpress-mysql
  MYSQL_USER: wordpress
  MYSQL_PASSWORD: wordpress