apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdF9wYXNzd29yZA== 
  MYSQL_DATABASE: d29yZHByZXNzLW15c3Fs
  MYSQL_USER: d29yZHByZXNzLWRi
  MYSQL_PASSWORD: d29yZHByZXNz