apiVersion: v1
kind: Secret
metadata:
  name: wp-secret
type: Opaque
data:
  DB_HOST: d29yZHByZXNzLW15c3FsOjMzMDY=
  DB_USER: d29yZHByZXNzLWRi
  DB_PASSWORD: d29yZHByZXNz
  DB_NAME: d29yZHByZXNzLW15c3Fs